modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "basicshields"
version = "${version}"
displayName = "BasicShields"
authors = "StellarWind22"
description = '''
Basic Shields adds vanilla-style shields to Minecraft for each material. All shields fully support banners!
'''
#logoFile = ""

[[dependencies.basicshields]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.basicshields]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.basicshields]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "basicshields.mixins.json"
